### ISSUE TITLE
Design a header menu and provide links to various subpages of the website

### ISSUE THREAD

**Issue by thekakamora** [MetricsDAO/xyz#10]
We need a menu on header to navigate to various pages on the website on desktop version as well as on mobile version. The first iteration of the menu can start linking to 
1. dashboard available at `/dashboard`
2. showcase available at `/showcase`
3. documentation available at `https://docs.metricsdao.xyz/` ( related issue #8 )

**Comment by thekakamora** [comment]
@[olafsnowman](https://github.com/olafsnowman) you can work on this issue. Please let me know if you change your plans then I'll assign this to another community member.

**Comment by olafsnowman** [comment]
@thekakamora sure, I'll start working on this issue.

**Comment by thekakamora** [comment]
@olafsnowman  we have second version of header (thin one) and it needs to be  updated along with the regular one - https://github.com/MetricsDAO/xyz/blob/main/app/components/app-header-skinny.tsx

**Comment by olafsnowman** [comment]
@thekakamora Updated skinny header as well.
