### ISSUE TITLE
Times and Status on Bounty Boards

### ISSUE THREAD

**Issue by davidenoch** [MetricsDAO/xyz#13]
The metrics bounty board entries (i.e individual bounty questoin page/card has two flaws in it that have been brought up several times, which I feel would be easy to address:
  1. The time should include the time zone. We have a very international crew so UTC is probably what should be used, but it should be on there. 
  2. The current week's bounties, which are still being worked on are labeled "completed". While this may be an accurate status report for other purposes, this is the board that the hunters (and hopefully a lot of new ones) see when they are thinking about entering a bounty, so it should not be listed as such.

**Comment by thekakamora** [comment]
@davidenoch the system that shows bounties is different one than this codebase. It has limited capabilities when it comes to configuring it.  Having said that I agree with both points you mentioned. 

We have plan to migrate bounties list to this web app and when we move it here we will have better control on how we show the information. These two requests will be considered when designing the new page.

**Comment by davidenoch** [comment]
Sorry, I was making the suggestion about the notion site, and was told to post here. That is something I would hope that is not a big deal to fix. Even editing manually is easy because there aren't that many questions. -potmo
