### ISSUE TITLE
Fix padding & margins of showcase page on mobile devices

### ISSUE THREAD

**Issue by thekakamora** [MetricsDAO/xyz#14]
The page showcasing all [analysts submissions ](https://metricsdao.xyz/showcase) is not properly showing up on mobile devices with small screens. Potentially requiring proper padding & margin settings. 

The following screenshot taken on an iPhone shows the alignment issues on the left side with content cutoff

![mobile_layout_issue](https://user-images.githubusercontent.com/86695148/170169300-94b6becd-fc30-40d2-8b37-aa02cb69afa6.jpeg)

**Comment by raygdev** [comment]
Hello @thekakamora! May I give this one a shot? This would be my first time doing this, so please bear with me!

**Comment by thekakamora** [comment]
@raygdev its all yours! please take it ser. Also say hi on discord(kakamora#2549) so that we can be touch with you.

**Comment by raygdev** [comment]
@thekakamora nothing renders to the page when pulling up the endpoint for showcase. It's attempting to make an api call with undefined environment variables. I can use the chrome browser from the link above if need be and supply the code in the file from that. Also noted a breaking change to the svg icons and content in each list item, when getting the main content center, the li content starts overflowing on the right at about 400px and lower. Tried to send a request to you, discord says you aren't accepting friends at this time. My discord(RayG#9660) if you'd like.

**Comment by thekakamora** [comment]
@raygdev I could not locate you our discord server (https://discord.gg/7w8mBbdg). If you are not on the server, please join and tag me in #general channel and I'll share the details required to setup algolia on your dev box.
