### ISSUE TITLE
Make Reviewers Reviews and Scores accessible

### ISSUE THREAD

**Issue by davidenoch** [MetricsDAO/xyz#15]
As both a reviewer, who tries to leave a useful piece of feedback to the bounty hunter and as a bounty hunter who craves feedback, I think it would be awesome to have this available.

**Comment by drakedanner** [comment]
Thanks for opening this issue!

I would love to display more data about the submissions and all interactions.

My understanding is that this issue relates to displaying the written feedback provided by reviewers as well as any other heuristics they use to score submissions.

Are there other / specific aspects that you think would be important to share?

**Comment by davidenoch** [comment]
Hi danner sorry didnt get back sooner. Well i like the points either in place of or in addition to the "stellar", "strong" etc. But I would like to read the graders' comments but yeah i would take the whole broken down score by rubric category too. (potmo if you dont know)

**Comment by thekakamora** [comment]
This needs enhancements to the APIs that populate data into algolia. I'll update it as soon as the enhancements are done and then an UI dev pickup this improvement.

**Comment by olafsnowman** [comment]
Hi @thekakamora, I want to work on this issue.

**Comment by thekakamora** [comment]
@olafsnowman feedback(`grading_notes`) from reviewers is available in algolia along with score (`overall_score`). You can design the UI to show them appropriately.

As multiple graders review the submissions, there will more than one note in the column `grading_notes`. When multiple notes are available for a submission they are delimited using  `<--review-delimiter-->`. See the example below with two grading notes.



```
{
      "key": "recTm9w5oQJMsrGcH",
      "program_name": "OlympusDAO",
      "question_number": 24,
      "question_title": "One with the OHM",
      "hunter_discord_id": "Hessamsh#9153",
      "created_at": "05/19/2022",
      "public_dashboard": "https://app.flipsidecrypto.com/dashboard/one-with-the-ohm-PKFllq",
      "question_start_date": "2022-05-13T00:00:00",
      "submission_due_date": "2022-05-20T00:00:00",
      "question_level": "Beginner",
      "question_display_title": "24 - One with the OHM",
      "overall_score": 8,
      "grand_prize": "",
      "submission_quality": "Strong",
      "grading_notes": "bad dataviz and could be more insightful (see jackguy for a good example)<--review-delimiter-->Redac",
```

**Comment by davidenoch** [comment]
This is so awesome! Huge improvement. I see Flipside is doing the same thing as well.
