### ISSUE TITLE
Make Showcase record titles better looking

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#16]
![image](https://user-images.githubusercontent.com/11461756/170356364-ec1fa137-6ac0-4e17-8d5b-8c683608e96c.png)

Would be cleaner if we could trim the question number from the title and display the program / project with an icon or at a second level.

This might be two issues:

- Trim question numbers
- Change how we display the program

If we feel that including the question number or ID is important, we could move it to the second layer of information along with the program.

**Comment by D0R11** [comment]
Hi @drakedanner, I would like to take on this issue.

**Comment by D0R11** [comment]
I would like to propose the following changes to the showcase page:

![image](https://user-images.githubusercontent.com/99073366/170711601-06701cf9-d467-4216-8a36-4609be81c66a.png)

1. Removing the program and the number from the title name
2. adding a program tag beside the title name that, if clicked, will automatically check the clicked program

Let me know your thoughts @drakedanner @thekakamora.

**Comment by thekakamora** [comment]
@D0R11 please start working on the issue. Here is some information to get started with 

This is a sample payload available for each submission. You can get title without program name & question id by referring to the field `question_title`. 

```
{
"program_name": "OlympusDAO",
      "question_number": 16,
      "question_title": "The OHMies",
      "hunter_discord_id": "lilypencal#7070",
      "created_at": "05/13/2022",
      "public_dashboard": "https://app.flipsidecrypto.com/dashboard/olympus-dao-16-the-oh-mies-0yjPhg",
      "question_start_date": "2022-05-06T00:00:00",
      "submission_due_date": "2022-05-13T00:00:00",
      "question_level": "Beginner",
      "question_display_title": "16 - The OHMies",
      "overall_score": 10,
      "grand_prize": "",
      "submission_quality": "Top Tier",
      "objectID": "f658415735262_dashboard_generated_id"
}

```

Regarding icons for programs, you can use the field `program_name` and pick up appropriate program icon. If you encounter an unknown `program_name` then pleas use a fallback icon.

**Comment by D0R11** [comment]
Apologies for the late reply. I'm working on it. Thanks!

**Comment by D0R11** [comment]
Added a PR

**Comment by thekakamora** [comment]
@D0R11  what you think of showing icons as I mentioned the comments above? I attached a screenshot of design from https://flipsidecrypto.xyz/discover/submissions. Can we do something similar ?

![image](https://user-images.githubusercontent.com/86695148/171102527-1298fc00-39a8-4f44-a9f5-800515b7a128.png)

**Comment by D0R11** [comment]
Sure. Shall we replace the tag beside the program title with the protocol logo? Or is it beside the author's name?

**Comment by D0R11** [comment]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/99073366/171989659-a61f279f-5412-4ad7-bb94-a0a8d615b8ac.png">

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/99073366/171989670-f38f7387-f91b-4e63-bf87-cfd5066894f0.png">

I manually downloaded the logos from google (since crypto-logos do not have OlympusDAO logos yet for some reason) but I did it like this. What do you think @thekakamora?
