### ISSUE TITLE
Display data about questions generated

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#17]
Questions are generated on https://bounty.metricsdao.xyz/ using Canny.

We should show data about...

- number of questions generated (per program & per user)
- unique number of authors (per program)
- numbers of questions used for challenges (per program & per user)
- etc 

---

We want to be able to display the volume of question generation, the active individuals, and the conversion rates from question to challenge.

**Comment by akbaridria** [comment]
Hi, i'd like to take on this issue and create a mockup from it. 

<img width="1671" alt="Screenshot 2022-05-27 at 20 52 39" src="https://user-images.githubusercontent.com/26589426/170793399-90c82c21-ffed-4d44-9cd7-df3b4a6412c8.png">

but it seems the suggestion from @thekakamora is more fit to add the new tab on dashboard page for question dashboard. another issue is getting data from canny, they had the APIs but, it seems it is only the raw data so, we have to calculate the data in the back. or anyone have some experience to pull the data form canny ?

**Comment by thekakamora** [comment]
I think we should add a tab to our dashboard, creating charts is easy but getting data is going to be a bit tricky. We need to understand how to extract required information from canny apis.  Here is the reference to APIs documentation - https://developers.canny.io/api-reference

**Comment by akbaridria** [comment]
Hi @thekakamora. i think i have some idea about pulling data from canny and integrate it with zoho.
We can use google app script that running every minute to pull data from canny to google sheet and then use google sheet to integrate it with zoho.

I have tried it by my self creating canny and zoho account to test it, it could be something like this.

1. Use google app script to pull data from canny API (we can scheduled running the script for every minute our hour)
<img width="927" alt="Screenshot 2022-05-28 at 15 17 22" src="https://user-images.githubusercontent.com/26589426/170817114-072a6979-29e7-4ed7-ba3d-f9e0b8cfa529.png">
2. Insert the data to google sheet
<img width="822" alt="Screenshot 2022-05-28 at 15 16 41" src="https://user-images.githubusercontent.com/26589426/170817143-789ee3ce-f6d7-44e9-b308-040c40e0c7c4.png">
3. Integrate it with zoho
<img width="1655" alt="Screenshot 2022-05-28 at 15 15 34" src="https://user-images.githubusercontent.com/26589426/170817157-cda2a237-d6bc-40a7-a396-733333626d29.png">
