### ISSUE TITLE
Display reviewer data on the dashboard page

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#18]
We could surface data related to:

- number of reviewers
- reviews per reviewer
- average scores given
- score distribution
- etc

---

Reviewers are an important participant in the MetricsDAO network - showing information about their behavior and outputs is high value for all participants

**Comment by thekakamora** [comment]
We have data about the following and this can be added to https://metricsdao.xyz/dashboard
1. number of reviewers
2. reviews per reviewer

but we are not recording the following in a structured way to surface on dashboards. We need to enhance our data capturing & review ecosystem to surface this information. 
3. average scores given
4. score distribution

**Comment by thekakamora** [comment]
The following metrics related to reviewers are added to the dashboard - https://metricsdao.xyz/dashboard
1. Number of unique reviewers
2. Number of submissions reviewed
3. Number of programs reviewed
4. Growth of reviewers
