### ISSUE TITLE
Add Discord link and Newsletter link

### ISSUE THREAD

**Issue by davidenoch** [MetricsDAO/xyz#26]
I suggest adding a discord icon next to the twitter and adding a button for the newsletter next to dashboard, showcase etc.

**Comment by jdaly13** [comment]
@fernando-RA @davidenoch - I think we can add the discord link but the header I believe has been recently updated - are you still looking to add a "newsletter" link?

**Comment by jdaly13** [comment]
I apologize for late reply on this
