### ISSUE TITLE
[public report]: If a user attempts a transaction while on Ethereum, it still allows it instead of switching networks

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#303]
### User Impacted

0x581BEf12967f06f2eBfcabb7504fA61f0326CD9A

### Discord ID (including number)

danner.eth#7297

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/11461756/217126676-aa3485ec-518b-45f8-8bd9-8090e9b59319.png">

As a user, I connected to dev.metricsdao.xyz using my Metamask. My Metamask is on the Ethereum chain. When attempting to do a transaction, I am not prompted to switch networks.

If a user continues this path, they may spend money sending a transaction on the wrong chain.

### Blocking

no it is not

**Comment by elisemarika** [comment]
we should prevent the user from failing in the first place and prompt them to switch networks when originally connecting to the app

**Comment by thehannahlerman** [comment]
I fixed this so it will show "Switch chain" on Ethereum, but it would still techincally allow users to attempt a transaction. Do we need more gating on this?

**Comment by elisemarika** [comment]
Catch the error and prompt a network switch is ideal, if feasible

**Comment by drakedanner** [comment]
This popped up in our Office Hours with operators as well

**Comment by sebruiz** [comment]
This was fixed in
https://github.com/MetricsDAO/xyz/pull/377
