### ISSUE TITLE
Can't create a public Marketplace [dep on N Badges]

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#311]
### User Impacted

0xBf17bE25a18c2F45fe4A8702b92B8dBd77872561

### Discord ID (including number)

elisemarika#8643

### Workflow Impacted

Analyze

### Feature Impacted

Create Marketplace

### Issue description

Who has permission to launch challenges?

- this section only allows me to select `Delegates only`
- this section should also include a dropdown option for `Anyone` which allows anyone to launch challenges and the Badger Contract Address and Badger Token ID inputs aren't needed for this selection
<img width="729" alt="Screen Shot 2023-02-07 at 5 41 12 PM" src="https://user-images.githubusercontent.com/93347510/217383816-1cc3c7f5-043f-4eb2-88a3-119bb9d288fd.png">

### Blocking

yes it is

**Comment by elisemarika** [comment]
Ed: the more elegant workaround is a toggle to say "public" which does that behind the scenes
Mason: Effort for a toggle is 20 minutes, very very low effort I just was under the impression everything was Badge gated
Ed: can build that UI real quick

**Comment by elisemarika** [comment]
@masonchain curious if that toggle support is ready for app team?

**Comment by nftchance** [comment]
The whitepaper did not have plans for a public toggle, as there are better solutions, and it adds additional bloat to the cost of every user. Instead, the recommendation and plan were just a marketplace with a zero balance / not-configured badge setup.

The balance required just needs to be set to zero and then it's public.

**Comment by masonchain** [comment]
As a temporary workaround, the upcoming v1.6.0 of the Labor Markets primitive can have a LaborMarket created with the delegate badge set to the zero address. Token ID does not matter, but when this badge is set to the zero address, anyone can create a request on the marketplace.

```
  delegateBadge: LaborMarketConfigurationInterface.BadgePair({
      token: address(0),
      tokenId: DELEGATE_TOKEN_ID
  }),
```

**Comment by nftchance** [comment]
**Status report:** In the process of finalizing [NBadge](https://github.com/nftchance/remus) a [contract update was required for Badger](https://github.com/FlipsideCrypto/badger/pull/130).

In preparation for the audit, a final feature-add is taking place for Badger, and then N-Badge will be ready to support. All code for N-Badge has been completed and finalized (as a model), and only [resolving dependency issues remain](https://github.com/FlipsideCrypto/badger/pull/181).

**Comment by elisemarika** [comment]
closing as duplicate to #362
