### ISSUE TITLE
[public report]: URL Structure Enhancement for Navigation

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#316]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217432505-66a88339-97a4-4eff-8c9f-9ca8815d8e9a.png)

As a user who can find markets by address, I struggle to find the market on the front end via the URL

Is there anything on-chain that dictates a challenge type?

![image](https://user-images.githubusercontent.com/11461756/217432695-17611165-c87b-4dfa-9841-f5a9fdd17c95.png)

![image](https://user-images.githubusercontent.com/11461756/217432747-c13a7a02-e30e-482a-a1c3-60aef4733453.png)

It is a "nice to have" to be able to navigate to these pages using the market address

### Blocking

no it is not

**Comment by elisemarika** [comment]
Come back to if we start to add more use case types OR pivot to a generic flow with labels for all the things

**Comment by drakedanner** [comment]
@bcinman is the change you implemented canon? can I close this?

**Comment by bcinman** [comment]
Yep, feel free to close 👍

**Comment by drakedanner** [comment]
Closed with @bcinman adjusting URLs to follow an `app/market/[address]` model 
![image](https://user-images.githubusercontent.com/11461756/221106173-5909741a-4a01-4ec3-b3bc-c316250e83a1.png)
