### ISSUE TITLE
Protocol chain Payments (End to end Rewards)

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#329]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

My Rewards

### Feature Impacted

Claim Reward

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217634608-b7ca347f-f562-43ae-84ef-d1b08af40d90.png)

It says I have 3 rewards but I don't think I should have any.

It shows 2 rewards and 2 pages without another page.

### Blocking

no it is not

**Comment by elisemarika** [comment]
known gap for 2/8

**Comment by PCWCFA** [comment]
I won't open a new issue, but the reward can be claimed. See this transaction for successfully claiming a reward https://polygonscan.com/tx/0xa07fe6d6f02023ba95efbab43514b8b3ecebf35a1f8bd21b7ed4623f2064f629, but then the reward remains on screen allowing a second claim which I assume to be unsuccessful because there was no accompanying transaction.

**Comment by drakedanner** [comment]
@masonchain taking a look

**Comment by elisemarika** [comment]
@masonchain any update on how we can get this one over the finish line?

**Comment by nftchance** [comment]
This transaction highlights that the user did not interact with the protocol: https://polygonscan.com/tx/0xa07fe6d6f02023ba95efbab43514b8b3ecebf35a1f8bd21b7ed4623f2064f629

as the destination address was address(0)

While there may be another deeper issue, at this time, the primary issue is that the build-to rewards is not established currently.

**Comment by masonchain** [comment]
Leaning towards the conclusion that the pending rewards Drake and PCWCFA were seeing had empty data as the contract address called and all parameters were null values.
