### ISSUE TITLE
[public report]: Claim to Review and Claim to Submit lock rMETRIC amounts

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#331]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217639907-5fab645d-f08b-4f5e-8238-41d7f682a630.png)

Shows transaction complete but does not indicate to me in any other way that I successfully claimed to review or that any rMETRIC balances changed

### Blocking

no it is not

**Comment by elisemarika** [comment]
Claim to review formula = 5 rMETRIC per submission. i.e. 5 x 100 = 500 rMETRIC to claim

Claim to submit formula = rMETRIC minimum required to submit on challenges, whatever that value is based on the Marketplace parameter

**Comment by termaatFlipside** [comment]
#455 Closes part of this.
#336 will cover the rest
