### ISSUE TITLE
[public report]: Submission count in sub-nav is wrong

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#333]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217643861-e2573683-b5c1-4b40-bbe0-a819cf13a6ff.png)

Says 0 but there is 1 shown and at least 2 on-chain

### Blocking

no it is not

**Comment by sebruiz** [comment]
I have a fix for this, just needs to be deployed
