### ISSUE TITLE
Too many confirmation modals

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#335]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

Navigating through the application is made difficult by the high amount of confirmation modals 

> Submit
> Modal Submit
> Metamask Submit 

I think we can remove the second confirmation is almost all cases 

### Blocking

no it is not

**Comment by bcinman** [comment]
This is kind of a limitation of web3 right now. In order for mobile wallets to work the contract write needs to be "prepared" and ready to write at the time of the user tapping a button. 

That means we can't do the IPFS upload and execute the write when that's finished. 

Hence we need a confirmation step in between.
