### ISSUE TITLE
[public report]: lack of redirects makes navigation confusing [dep on refactor]

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#336]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Other

### Issue description

In many cases I do an action and am not re-directed to the next page nor am i given a path to get to the page.

ie: as a user i want to launch a challenge

First I create a marketplace
Then I have to navigate to all marketplaces 
Then I need to find that marketplace 
Then I need to crate a challenge

If I then want to review the challenge I created, 
Then I have to navigate to all marketplaces 
Then I need to find that marketplace 
Then I need to find that challenge

### Blocking

no it is not

**Comment by elisemarika** [comment]
Redirect to page you just created with message about reload it doesn't exist yet << display polygonscan link, display error (if feasible)

- Create marketplace - to that marketplace
- Launch challenge - to that challenge
- Claim to submit - to that challenge
- Claim to review - to that challenge
- Submit - to that challenge / submissions tab
- Review - to that submission you just scored
- Claim reward - to my rewards list
- Add payout address - to payout address list

**Comment by sebruiz** [comment]
I kinda like this idea: On the, say, labor market page, show some kind of banner (maybe with a loading spinner) indicating that we are "indexing". In the background, do some polling every 5-10 seconds to see if we're done indexing yet, and if we are, populate the data.

**Comment by drakedanner** [comment]
For 

> Review - to that submission you just scored

This re-direct feels okay but a "Review Next Submission" button would mean that the user doesn't need to click out of that page back to the index and then into a different submission

If re-direct back to submission then:

- land on submission
- see recently applied score
- click back to challenge
- click into submission
- view submission
- click review
- apply score

If re-direct back to submission + next button:

- land on submission
- see recently applied score
- click "Review Next"
- view submisison
- click review
- apply score

I suppose this only removes one click, but it lets the user stay in their flow of reviewing submissions to a specific challenge

**Comment by elisemarika** [comment]
@drakedanner how about this...

Re-direct back to the Challenge / Submissions list
- land on Submission list view
- select next submission to review instead of being forced to the "next"

**Comment by drakedanner** [comment]
Chance is noting that WAGMI has functionality to pull data from the event execution rather than relying on the indexer for cases like Labor Market creation and Challenge creation.

This would allow re-directs on these creations

**Comment by bcinman** [comment]
Redirect has been added to the labor market creation flow. Working through the rest of the flows this week.

**Comment by sebruiz** [comment]
Will be addressed in upcoming refactor tickets
