### ISSUE TITLE
Authors should be able to enter more than one submission on a single Brainstorm Challenge [dep on maxSubmissions on Requests]

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#345]
### User Impacted

0xBf17bE25a18c2F45fe4A8702b92B8dBd77872561

### Discord ID (including number)

elisemarika#8643

### Workflow Impacted

Brainstorm

### Feature Impacted

Enter Submission

### Issue description

When participating in Brainstorm and Analytics Challenges, Authors/Analysts should be able to submit 1 to man (submissions) on a single Challenge. This is a low effort task and it's likely that someone has many interesting and unique ideas to share. Flipside's ProAd team will also be power users of this feature, and it's extremely likely that a single person will enter a number of ideas on behalf of themselves or others to be prioritized.

### Blocking

yes it is

**Comment by nftchance** [comment]
This would significantly increase the risk factor of the overall protocol with no obvious or significant benefit. Effectively, this feature promotes the creation of spam and significantly lowers the frictional barrier between attribution, access, and financial spend to $rMETRIC.

Is there further documentation or conversation that can be referenced for this?

**Comment by elisemarika** [comment]
@nftchance @drakedanner I think maxSubmissionsPerUser is reasonable - if we did that, is there a cap you'd want to enforce? also, should this be a Marketplace parameter?

**Comment by nftchance** [comment]
> if we did that, is there a cap you'd want to enforce?

My `personal` maximum was one, as even allowing `n` submissions increases the risk factor by an exponential of `n` submissions. Even given it is a marketplace parameter, this is very risky and is the precise reason support for Delegatable was added.

From everything that I can see here, this is effectively asking to increase the limit so that certain individuals can "spam" submissions while that has been the primary thing we have been trying to avoid with this as we do not have an endless or free `grading` system.

Even as a parameter, I cannot see the justification for such risk.

**Comment by drakedanner** [comment]
I think we need to better understand this use case for multiple submissions.

For Brainstorms:
- We want to generate a lot of questions 

For Analytics:
- Someone may want to update their submission

@elisemarika is this a case where we should gather stakeholders to discuss and understand their views?

**Comment by elisemarika** [comment]
@drakedanner absolutely - let's huddle with Aaron and GJ on this one to validate our assumptions. I'm pretty confident about them given 1+ year of bounty support, but let's verify

**Comment by elisemarika** [comment]
![Image](https://user-images.githubusercontent.com/93347510/219124252-69350af1-02c5-431b-aa39-6b4a84bb41cb.png)

**Comment by elisemarika** [comment]
@nftchance @masonchain @gnomadic no longer relevant since we deprecated Brainstorm, gonna close/archive this one unless you see a reason to keep it open

**Comment by gnomadic** [comment]
wooo closing it
