### ISSUE TITLE
[public report]: No formatting on Marketplace and Challenge prompts

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#346]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Brainstorm

### Feature Impacted

Launch Challenge

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217857612-2212280b-4ca2-415c-9980-25249fee5ed5.png)

I used line breaks and tried dashes/asterisks to see if markdown works.

Everything ending up jumbled together

would be good to expand/collapse too
https://beta.metricsdao.xyz/app/brainstorm/m/0x2a7448ed25104ee6c470b28b1772c7d2da3c93c7 

see comments

### Blocking

no it is not

**Comment by elisemarika** [comment]
markdown or HTML, anything -- want by public GTM basically end of Feb

**Comment by elisemarika** [comment]
@sebruiz saw this marked closed, is it done done?
