### ISSUE TITLE
[public report]: No Front End feedback when trying to Signal on something already signalled

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#348]
### User Impacted

0xc6Ac8FC10242771eA79B1Bdbb4d72f775AF9587F

### Discord ID (including number)

danner.eth

### Workflow Impacted

Analyze

### Feature Impacted

Claim to Review

### Issue description

![image](https://user-images.githubusercontent.com/11461756/217862493-79477e23-299f-4242-a422-ed0c2e428293.png)

I tried to signal to review and i did not get a metamask popup 

### Blocking

yes it is

### Relevant log output

```shell
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. 
Object
code
: 
-32603
data
: 
code
: 
3
data
: 
"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b4c61626f724d61726b65743a3a7369676e616c5265766965773a20416c7265616479207369676e616c6564000000000000000000000000000000000000000000"
message
: 
"execution reverted: LaborMarket::signalReview: Already signaled"
[[Prototype]]
: 
Object
message
: 
"Internal JSON-RPC error."
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
```

**Comment by elisemarika** [comment]
On hold until we have better error reporting -- need to figure out how to handle this when we allow unlimited submissions on a single challenge because they need to signal for each submission

**Comment by nftchance** [comment]
A user only signals at the `Request` level.

A Reviewer only specifies the number of requests they will be grading, but never specifically which submissions they will be grading.

**Comment by elisemarika** [comment]
@nftchance @drakedanner we were conflating claim to submit and claim to review, sorry for the confusion. the question is, if we allow more than 1 submission per challenge (some max per user) we'll need to allow them to signal each time before submitting (many per challenge). so that UX will need to be different than how we handle claim to review (which is once per challenge)

**Comment by nftchance** [comment]
While I still do not think increasing the likelihood of attacks with increased maximum submissions is a good idea, why would the solution not be to signal the level of intent at the signaling time?

A cyclical pattern introduces lots of user friction, no?

**Comment by masonchain** [comment]
@sebruiz Confirming this is now being caught in the transaction prep?

**Comment by sebruiz** [comment]
> @sebruiz Confirming this is now being caught in the transaction prep?

Should be
<img width="788" alt="image" src="https://user-images.githubusercontent.com/84731260/218869514-d9697f5e-e501-44ae-bc82-81bfade4059d.png">
