### ISSUE TITLE
[public report]: Marketplace blockchain/project icons have bad formatting

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#355]
### User Impacted

0xBf17bE25a18c2F45fe4A8702b92B8dBd77872561

### Discord ID (including number)

elisemarika#8643

### Workflow Impacted

Analyze

### Feature Impacted

Other

### Issue description

Marketplace blockchain/project icons have bad formatting in the Marketplaces list and dedicated Marketplace page

**Beta app**
<img width="976" alt="Screen Shot 2023-02-09 at 2 31 38 PM" src="https://user-images.githubusercontent.com/93347510/217935478-e0ea1e1e-aacc-4b69-8319-fe8008015d92.png">

**Idea**
Maybe something more like this? thinking when you click +3 it will expand and show them
<img width="458" alt="Screen Shot 2023-02-09 at 3 47 44 PM" src="https://user-images.githubusercontent.com/93347510/217935775-25ad4117-a78f-4ba3-9dfc-2cab55a131a3.png">

### Blocking

no it is not

**Comment by drakedanner** [comment]
https://www.loom.com/share/f7efdeb2787b424fa83f7a220f4998ff

Not sure if we want to do a new ticket or move this one back @termaatFlipside @elisemarika 

When I click the number to expand, it expands but then re-directs to the View Marketplace page

**Comment by termaatFlipside** [comment]
@drakedanner Either works. 

Ideally eveything else is a link except the project icons correct?

**Comment by termaatFlipside** [comment]
@drakedanner Changed to show on hover instead
