### ISSUE TITLE
Allow users to open a question in a new tab in brainstorming phase

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#36]
currently, opening a question in a new tab (accessing a question by its distinct link) takes you to an empty page. https://discord.com/channels/902943676685230100/903338987022876702/999676970059182110

![image](https://user-images.githubusercontent.com/11461756/180239595-88ee86ac-7875-49c1-9828-22ee9b2f6e88.png)

**Comment by D0R11** [comment]
I'll check this one out and get back to you

**Comment by drakedanner** [comment]
Hey @D0R11 I moved it here https://github.com/MetricsDAO/bounty_app/issues/9
