### ISSUE TITLE
[public report]: Brainstorm Create Private Marketplace Confirmed by Transaction But Not Actual Creation in App

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#366]
### User Impacted

0xe95608B6a7f97bf5D076F0594EEe07e77b9781b7

### Discord ID (including number)

PCWCFA#0438

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

Creating a delegated marketplace appeared successful on chain https://polygonscan.com/tx/0xa5b939f43279319186f6ad6d31018f3bd8cd149355452ccb99c3cfa6eac914d0, but the market creation screen did not advance past the modal that contains the Create and Cancel buttons. 

After I closed the modal by clicking on the underlying screen, the app returned me to the Brainstorm marketplace creation screen containing all the information that I just entered. 

When I navigated back to the Brainstorm page, I could not see my marketplace.

### Blocking

yes it is

**Comment by elisemarika** [comment]
@gnomadic @bcinman probably indexer delay?

**Comment by gnomadic** [comment]
yeah.  We gotta have a jam on how to handle this - sometimes there is a delay, and sometimes it seems there are issues just picking up marketplace creations.

**Comment by gnomadic** [comment]
hey this is a known issue, and we're tracking it elsewhere so we're gonna close this one.  Do appreciate the report, thank you!
