### ISSUE TITLE
Request: UI Improvement in the Challenge Creation Screen Mandatory Fields

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#369]
Please consider making the start and end times more obviously mandatory. Now, it's not obvious the fields are mandatory until the user selects Next. 

![image](https://user-images.githubusercontent.com/67286305/218193512-6acd8fbe-5f05-4ea9-9e6c-cce59ea81eb0.png)

**Comment by gnomadic** [comment]
thanks!  we'll huddle with our design team on this one

**Comment by elisemarika** [comment]
@termaatFlipside note Madison's suggestion: Quick fix to this would be adding an asterisk to all required fields.
