### ISSUE TITLE
Challenge page is missing Participants tab

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#370]
### User Impacted

0xBf17bE25a18c2F45fe4A8702b92B8dBd77872561

### Discord ID (including number)

elisemarika#8643

### Workflow Impacted

Analyze

### Feature Impacted

Other

### Issue description

Challenge page is missing Participants tab
![Screen Shot 2023-02-10 at 3 45 24 PM](https://user-images.githubusercontent.com/93347510/218194255-a450a902-45c1-4ba1-96fc-5d1ae3b8f5a4.png)

### Blocking

no it is not

**Comment by termaatFlipside** [comment]
@elisemarika Who should be listed? 

I currently have a version with people that have submitted and should be able to add people that have reviewed as well.

Just claiming I don't think we store the time info for that right now

**Comment by elisemarika** [comment]
@termaatFlipside users who submitted and those who reviewed as well is a great start. including users who claimed to submit or claim to review is also critical because it helps users decide if they want to claim and compete with those others and also helps inform how the reward pool might be impacted (spread across a small group or a large group)

**Comment by nftchance** [comment]
🚨 **This issue is currently hard-blocked and cannot progress.**

Progress has been made, but cannot be completed until we are capturing claims.

**Comment by sebruiz** [comment]
Note: Might be easier to accomplish with the activity changes done here:
https://github.com/MetricsDAO/xyz/issues/364

**Comment by elisemarika** [comment]
@sebruiz @thehannahlerman what's the latest on being able to store claim activity as part of #364 ?
