### ISSUE TITLE
[public report]: Timeline and deadline validations for all actions [need app on 1.6]

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#371]
### User Impacted

0xe95608B6a7f97bf5D076F0594EEe07e77b9781b7

### Discord ID (including number)

PCWCFA#0438

### Workflow Impacted

Brainstorm

### Feature Impacted

Launch Challenge

### Issue description

Technically not a defect, but the challenge creation allows the creation of a challenge where the review period ends before the start of the analytics period. Here's the transaction that shows the challenge was created as specified below: https://polygonscan.com/tx/0x8fcaad787243bccba03ecd3e0e6db4100f82bcdc91830e937767f5696a632f3c.

![image](https://user-images.githubusercontent.com/67286305/218194962-97180ffc-8fd1-4a34-be4e-630a99a4fe3c.png)

### Blocking

no it is not

**Comment by PCWCFA** [comment]
Related is the end date can be earlier than the start date. Here's the creation of a challenge: https://polygonscan.com/tx/0x4f59e4e4c69d601ff18bc5abb00b008e26c84d202cd73a3dd10d3a879daddd61. 

![image](https://user-images.githubusercontent.com/67286305/218196585-c0eed650-44e7-4fe0-8222-940fd19e4d0d.png)

**Comment by nftchance** [comment]
Originally this was planned to be handled at the app layer; however, with confirmation that it may slip through the cracks and exposure to auditing practices, it will be best to enforce quality checks of each parameter moving forward @masonchain.

https://github.com/FlipsideCrypto/labor-market/blob/main/src/LaborMarket/LaborMarket.sol#L25

> While this should be handled by the app layer with an error system, this should first be prevented at the protocol level, which is not the case today.

**Comment by elisemarika** [comment]
@nftchance @masonchain , @sebruiz has also reported this issue. want to clarify if these validations are something protocol will handle or something app team should prioritize solving? https://github.com/orgs/MetricsDAO/projects/5/views/6?pane=issue&itemId=20379326

**Comment by sebruiz** [comment]
> @nftchance @masonchain , @sebruiz has also reported this issue. want to clarify if these validations are something protocol will handle or something app team should prioritize solving? https://github.com/orgs/MetricsDAO/projects/5/views/6?pane=issue&itemId=20379326

I think we'll want it in both the app and the protocol

**Comment by masonchain** [comment]
This is now caught in the next version of LM primitive.

We require the signal expiration to be greater than the current time, the submission expiration to be greater than the signal expiration, and the enforcement expiration to be greater than the submission expiration.

**Comment by drakedanner** [comment]
https://github.com/MetricsDAO/xyz/issues/437

**Comment by masonchain** [comment]
The contract now checks they are in chronological order and valid. We require: 
	- signal expiration to be > current timestamp
	- submission expiration > signal expiration
	- enforcement expiration > submission expiration.
