### ISSUE TITLE
[public report]: committed submissions number button background

### ISSUE THREAD

**Issue by anmins** [MetricsDAO/xyz#372]
### User Impacted

0xCeDbdc855c4eE8654fFC1De3D86a1F0E86bE74B8

### Discord ID (including number)

Angela__#0097

### Workflow Impacted

Analyze

### Feature Impacted

Claim to Review

### Issue description

When you select a number the selected button, the background turns grey. I think it should be blue, the grey makes me think that there is some problem with my selection.

### Blocking

no it is not

**Comment by gnomadic** [comment]
![Image](https://user-images.githubusercontent.com/7825326/218805212-e90657be-d578-458d-b6ee-123af045e17d.png)

Can we make the buttons blue instead of grey?
