### ISSUE TITLE
Display overall score and winners after peer review completes

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#373]
Display overall score and winners after peer review completes

Challenge page:
https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=2619%3A55330&t=joZFMQxSOidRZ5Nq-0 

Submission page: 
https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=2619%3A55783&t=joZFMQxSOidRZ5Nq-0

**Comment by elisemarika** [comment]
@sebruiz confirming intent that any tiebreakers favor the submission that came in sooner

**Comment by masonchain** [comment]
@elisemarika Are tie breakers needed? Comparing submissions to other submissions is sorting which we are incapable of doing on-chain.

**Comment by elisemarika** [comment]
@masonchain app layer needs tie breaker logic for when two submissions have the same overall score, and the intention is that the reward goes to the submission that came in first

**Comment by elisemarika** [comment]
we don't need tiebreakers with our current enforcement criteria - not waiting on protocol dev

**Comment by drakedanner** [comment]
Tiebreaks are split automatically by the enforcement criteria that we are using

**Comment by elisemarika** [comment]
@sebruiz given we don't need tie breaker logic, what's the latest on this one?
