### ISSUE TITLE
[public report]: Challenge Submission Text Greater Than One Line is Not Wrapped

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#375]
### User Impacted

0xe95608B6a7f97bf5D076F0594EEe07e77b9781b7

### Discord ID (including number)

PCWCFA#0438

### Workflow Impacted

Brainstorm

### Feature Impacted

Enter Submission

### Issue description

Submission text > 1 line is not wrapped.

![image](https://user-images.githubusercontent.com/67286305/218495548-4159833a-7122-498b-a618-69665ea107ec.png)

### Blocking

no it is not

**Comment by gnomadic** [comment]
this is related to but different than: https://github.com/MetricsDAO/xyz/issues/346
