### ISSUE TITLE
No loading indicator when submitting a submission

### ISSUE THREAD

**Issue by sebruiz** [MetricsDAO/xyz#381]
### User Impacted

sruiz

### Workflow Impacted

Brainstorm

### Feature Impacted

Enter Submission

### Issue description

The "Next" button when submitting a submission hangs for a while (uploading to IPFS) with no indication that there is loading happening.
<img width="526" alt="image" src="https://user-images.githubusercontent.com/84731260/218532130-d7165eae-2ce3-485c-9740-478b41cba249.png">
 

### Blocking

no it is not

**Comment by gnomadic** [comment]
feel free to reuse the loading bar from create challenge flow!

**Comment by elisemarika** [comment]
@termaatFlipside note Ed's suggestion above, does that feel right/easy to reuse?

**Comment by termaatFlipside** [comment]
@elisemarika yes, it does

**Comment by termaatFlipside** [comment]
Ended up just indicating loading on the button (done elsewhere and made a bit more sense)
