### ISSUE TITLE
Remove references to projected rewards

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#382]
We need to hook up the projected rewards values when viewing a Challenge. 

From @nftchance : Just show the distributions set in the enforcement, and multiply it by the total value of the request.   voila.  handled at the app layer

**Comment by nftchance** [comment]
To get ahead of the ball on this one, this is the distribution of those falling within that category and not relative to their payment. To support a relative projection, we **need** to add a `maxSubmissions` to requests.

**Comment by elisemarika** [comment]
@nftchance thank you! we can tackle this app side once we have maxSubmissions on Requests cc @gnomadic

**Comment by gnomadic** [comment]
I might have missed something - isn't max submissions on a request basically a claim limit?  Are we going to do that?

**Comment by elisemarika** [comment]
@gnomadic maxSubmissions means a single user can only submit n times on the same challenge
![Screen Shot 2023-02-16 at 1 31 08 PM](https://user-images.githubusercontent.com/93347510/219455873-cd2c0298-ec5e-4ae8-a76d-a188b31ad8d3.png)

**Comment by gnomadic** [comment]
awesome I was missing something -thank you!

**Comment by drakedanner** [comment]
De-scope projected rewards -- 

Ticket `Projected rewards formulas per Reward Curve [dep on maxSubmissions on Requests]` being renamed
