### ISSUE TITLE
Badger badge gating for "claim to review" button

### ISSUE THREAD

**Issue by sebruiz** [MetricsDAO/xyz#384]
### User Impacted

sruiz

### Workflow Impacted

Brainstorm

### Feature Impacted

Claim to Review

### Issue description

We can hide the "claim to review" button by checking if a user has the badge they need (i.e. delegate badge). We'll need a new hook for this.

### Blocking

no it is not

**Comment by elisemarika** [comment]
great one @sebruiz , we'll want gating for all action buttons based on permission reqs - badge or rMETRIC

**Comment by mahgillis** [comment]
How do we feel about something like this [https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=5445%3A38986&t=LfsLueRKCZaMmDo6-1](url)

**Comment by elisemarika** [comment]
@mahgillis love that! @sebruiz doable? [https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=5445%3A38986&t=LfsLueRKCZaMmDo6-1](https://github.com/MetricsDAO/xyz/issues/url)
