### ISSUE TITLE
Reviewer Workflow is not smooth

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#387]
As a user who is performing Reviews, I have scored a submission and want to score the next submission

To do this I must navigate "back" then navigate "in" when it feels like I want to navigate "next"
![image](https://user-images.githubusercontent.com/11461756/218628115-d0ec6b4f-d7f5-473b-b672-70b5d16e09e1.png)

**Comment by elisemarika** [comment]
@drakedanner we discussed this in the redirect issue with the team on Friday, we had decided that after you score you'll be redirected back to the submission you just scored..sounds like you feel like you should actually redirect back to the all submissions list? here's the comment where we outlined all of those for @thehannahlerman https://github.com/MetricsDAO/xyz/issues/336#issuecomment-1426137793
