### ISSUE TITLE
Separate signal stakes for claim to submit and claim to review to fix 0 rMETRIC req to submit issue [need app on 1.6]

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#390]
**Current Issue**
We have one hard coded signal stake value at the app layer which applies to both claim to submit and claim to review. The signal stake = 5, which is problematic for Marketplaces where the minimum rMETRIC balance required to submit is set to 0. Users think they don't need any rMETRIC to participate, but due to the signal stake = 5 they're actually forced to lock 5 rMETRIC to claim to submit

**Requirement**
- Allow signal stake = 0 for claim to submit
- Continue to enforce signal stake = 5 per submission committed to scoring for claim to review

**Proposed Solution**
Break out the signal stake into two separate signal stakes, one for claim to submit and one for claim to review
- Claim to submit signal stake = min. rMETRIC balance (Marketplace parameter)
- Claim to review signal stake = 5

**Comment by nftchance** [comment]
This is not currently supported at the protocol level. 

While it will not be advised that others be running Labor Markets with 0 reputations required, it does suffice as a way to bootstrap the creation of providers and, in turn, maintainers.

The proposed solution is feasible; however, given that configuration, it is unlikely that all submissions would be graded as there is no limit to botting or spamming.

It has been recommended by the primitive team that a `maxSubmissions` be added to each `Request` in V2, which would make this safer and more manageable while providing a good service and maintaining the health of the protocol.

Today, `signalStake` can be set as `0` which means submission and reviewing are both at 0.

**Comment by masonchain** [comment]
V1 now has the two signals broken out into provideStake and reviewStake, set at the LaborMarket level.

```
    struct LaborMarketConfiguration {
        string marketUri;
        address owner;
        Modules modules;
        BadgePair delegateBadge;
        BadgePair maintainerBadge;
        BadgePair reputationBadge;
        ReputationParams reputationParams;
    }

    struct ReputationParams {
        uint256 rewardPool;
        uint256 provideStake;
        uint256 reviewStake;
        uint256 submitMin;
        uint256 submitMax;
    }
```

**Comment by elisemarika** [comment]
thank you! two signals values are necessary because having a single value of 0 would break the claim to reward flow in the app

**Comment by masonchain** [comment]
Supported in Labor Market v1.6.0.

When creating a Labor Market, the ReputationParams in LaborMarketConfig, has provideStake and reviewStake parameters that facilitate different stake amounts for providing and reviewing.

**Comment by sebruiz** [comment]
1.6.0 upgrade enables this
https://github.com/MetricsDAO/xyz/pull/452/files#diff-119b008b39a57b7d80c61bb765185f7c1eb08d87d18f8381f0d88fd93fdd3321R48

**Comment by drakedanner** [comment]
Likely for a future ticket but want to capture:

- could the minimum rMETRIC match the claim to submit stake, should it?
- or should it be a distinct input?
