### ISSUE TITLE
[public report]: Claim to Review Does Not Open Wallet

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#393]
### User Impacted

0xe95608B6a7f97bf5D076F0594EEe07e77b9781b7

### Discord ID (including number)

PCWCFA#0438

### Workflow Impacted

Analyze

### Feature Impacted

Claim to Review

### Issue description

Trying to claim https://dev.metricsdao.xyz/app/analyze/m/0x1515455ca7842941dd1a90ae114cb4cf50397fd6/sr/1/review?quantity=10 results in no visual notification of failure, but the console shows some of error. 

![image](https://user-images.githubusercontent.com/67286305/218853570-eb67faa2-8c56-44b0-8a26-12a4cdd2552c.png)

### Blocking

yes it is

**Comment by elisemarika** [comment]
@gnomadic any idea what that error means?
