### ISSUE TITLE
UI Improvement: Show Wallet Add Without Refresh

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#394]
Right after adding the test wallet, this is the wallet list screen: 

![image](https://user-images.githubusercontent.com/67286305/218854418-eb120332-4bdc-4a32-a74c-a9de10ea63ba.png)

It takes reloading the screen (navigating to landing -> rewards -> payout addresses) to see that the wallet was added.

**Comment by elisemarika** [comment]
@termaatFlipside is this feasible?

**Comment by termaatFlipside** [comment]
@elisemarika I believe so
