### ISSUE TITLE
Breadcrumbs or some sort of back button to clarify where you are

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#420]

**Comment by termaatFlipside** [comment]
2/20 note: in design sprint

**Comment by mahgillis** [comment]
@termaatFlipside [here](https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=5577%3A40294&t=o789MD5HR3vQ4zEH-1) is a link to the back / breadcrumb navigation. Note that each page will need more spacing/room at the top to accommodate for this.
