### ISSUE TITLE
Showcase page (App home)

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#430]
We're reducing Ecosystem page scope to only include Showcase. Showcase will include Top Submissions as the single view here: https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=5381%3A37121&t=4iaIE2gCtuCgQVu6-0

**Comment by elisemarika** [comment]
will do after end to end rewards are complete

**Comment by termaatFlipside** [comment]
@elisemarika is it just the one table on showcase? asking bc the post its seem to reference the other tables

**Comment by elisemarika** [comment]
> https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=5381%3A37121&t=4iaIE2gCtuCgQVu6-0

@termaatFlipside yes we heavily reduced scope, so it's just the Top Submissions table and search/filter component in the updated Figma page
