### ISSUE TITLE
Do ASAP: Updating contract version to latest (1.6)

### ISSUE THREAD

**Issue by thehannahlerman** [MetricsDAO/xyz#437]
There is a new version of the contract that allows users to submit and claim multiple times. We should update our dependency and also change gating to allow a user to submit and claim multiple times on a service request. 

@masonchain @nftchance Anything else you can think of that was updated and needs to be reflected in the app?

**Comment by nftchance** [comment]
@masonchain Lead here, please -- Looking for scope to parity of 1.6.~ pre-2.0.

**Comment by drakedanner** [comment]
@masonchain is working on publishing the package and getting some docs together for this.

**Comment by masonchain** [comment]
1.6.0 is ready to implement and just requires dropping the DB and migrating to the new version.

1.6.0 does not support multiple submissions and claims yet as I was under the impression this [functionality is still tabled](https://github.com/orgs/MetricsDAO/projects/5?pane=issue&itemId=20122410). @elisemarika Can you give some insight on this functionality?

**Comment by nftchance** [comment]
To confirm, multiple submissions are tabled (for now).
