### ISSUE TITLE
Legacy and new app updates for public XYZ by 3/6

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#458]
The push here is to start to build momentum for the eventual full launch and to show off all the awesome stuff that is happening. The new home page does a great job of showing this off.

Sequence
- Deploy legacy app to [legacy.metricsdao.xyz](http://legacy.metricsdao.xyz/)
- Code change to update “Launch App” link to notion page
- Deploy dev to main to put new app on https://metricsdao.xyz/
- Code change to update “Launch App” to point back to app in dev branch (https://beta.metricsdao.xyz/ )
- Resume building/testing on dev branch (https://beta.metricsdao.xyz/ )

**Comment by sebruiz** [comment]
@elisemarika do you have a link to the Notion page and a description of what the button should say and look like?

**Comment by elisemarika** [comment]
@sebruiz here's the Notion page link: https://metricsdao.notion.site/Bounty-Programs-d4bac7f1908f412f8bf4ed349198e5fe

all buttons can look the same as they currently do, there are a number of them which I'll point out here. These can all link to the Notion page so we avoid anyone entering the app too early

Launch App<< Main nav. Update copy to `View Bounties`
![Screen Shot 2023-03-01 at 10 31 19 AM](https://user-images.githubusercontent.com/93347510/222186263-81a7b6ae-c829-44b7-8160-f272db715131.png)

Explore the Ecosystem << Homepage
![Screen Shot 2023-03-01 at 10 32 12 AM](https://user-images.githubusercontent.com/93347510/222186359-a8bfca01-51d4-47e3-82f1-43860ca83b60.png)

Launch App << Homepage
![Screen Shot 2023-03-01 at 10 32 50 AM](https://user-images.githubusercontent.com/93347510/222186538-256b281b-4e2f-4f1f-ab78-47b18fc28dfc.png)

Launch App << Footer. Update copy to `View Bounties`
![Screen Shot 2023-03-01 at 10 33 18 AM](https://user-images.githubusercontent.com/93347510/222186807-1fdfe506-913c-49b6-b064-163f443dfc58.png)

Explore the Ecosystem << Partner With Us page
![Screen Shot 2023-03-01 at 10 34 09 AM](https://user-images.githubusercontent.com/93347510/222186943-e4919c23-0c3c-4217-bc25-bc1bb11582cb.png)

Explore the Ecosystem << Partner With Us page
![Screen Shot 2023-03-01 at 10 34 39 AM](https://user-images.githubusercontent.com/93347510/222187048-184216ea-056a-4f62-8984-817e9b944b9e.png)

**Comment by elisemarika** [comment]
@sebruiz triple confirming we can maintain /showcase and /dashboard on legacy so the MDAO team can link to these from the Notion page

**Comment by sebruiz** [comment]
Yes!
