### ISSUE TITLE
Prevent users from scoring their own submission up front

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#463]
**Problem**

The app currently lets me **attempt** to score a submission I submitted, which should not be the case. The intent is that you cannot score your own submission in an effort to prevent muddling with overall score results, so don't let me try and fail here

I assume this error message is triggered since I'm trying to score my own?

Example: https://beta.metricsdao.xyz/app/market/0x61a97cb0ec9104ef06ebfe7b8cdbc377f4a8f908/submission/4 
Connected wallet: 0xBf17bE25a18c2F45fe4A8702b92B8dBd77872561

<img width="1724" alt="Screen Shot 2023-03-02 at 11 53 54 AM" src="https://user-images.githubusercontent.com/93347510/222498240-7f29eb6b-cf57-4b9d-9366-2593812ad4c0.png">

<img width="1721" alt="Screen Shot 2023-03-02 at 11 56 43 AM" src="https://user-images.githubusercontent.com/93347510/222498368-9c4da4e8-8681-47b3-a66e-eec4a998a239.png">

**Solution**
- Hide the Review & Score button in this case (we shouldn't show the button at all if it's not an action they can take). Idea from Bryan: https://github.com/MetricsDAO/xyz/issues/463#issuecomment-1452340690

**Comment by bcinman** [comment]
Agree. It might be nice to have a "Your Submission" indication in place of the button? Not sure if that's necessary though
