### ISSUE TITLE
Bug - submit max for labor market is broken

### ISSUE THREAD

**Issue by sebruiz** [MetricsDAO/xyz#508]
Related to: coercing into a number with z.coerce(). Maybe need to make a checkbox that allows a user to select the maximum value.

**Comment by elisemarika** [comment]
I don't think we need to do this given we are deprecating rMETRIC..right? cc @gnomadic

**Comment by gnomadic** [comment]
we might still want min/max fields for N-Badge badges - I think we'd want this logic but in a different place

**Comment by elisemarika** [comment]
@bcinman note the above for N Badge ^

**Comment by elisemarika** [comment]
closing this cause we will handle in N Badge issue
