### ISSUE TITLE
Unable to claim to submit with a new wallet

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#555]
### User Impacted

0x431F5fC03B4D8968EfC18458A2637C05a6731A00

### Discord ID (including number)

gnomadic#8135

### Workflow Impacted

Analyze

### Feature Impacted

Claim to Submit

### Issue description

I created a new wallet in metamask (top right favicon -> `+ Create Account` and gave it some MATIC.  This wallet does hold one badger badge, but it's not relevant for this, and no rMetric.  

When I visit a challenge in a marketplace with no rMetric requirements: https://beta.metricsdao.xyz/app/market/0xdBA4CcE924040EB15887A539b9Cb9Ffdf0a4aDA5/request/1/prereqs

I see

<img width="1278" alt="Screen Shot 2023-03-17 at 2 41 24 PM" src="https://user-images.githubusercontent.com/7825326/225993483-9c663021-b0fb-4acb-8140-8d1990b49093.png">

That is expected - this wallet is not a reviewer, but it should be able to submit.

When attemping to claim to submit, I see:  
<img width="377" alt="Screen Shot 2023-03-17 at 2 41 29 PM" src="https://user-images.githubusercontent.com/7825326/225993535-8473108d-fc01-4957-913a-5216be61a6be.png">

### Blocking

yes it is

**Comment by gnomadic** [comment]
Triage here, https://flipsidecrypto.slack.com/archives/C0459AQFT51/p1679079415077069

looks like an issue with provideStake defaulting to 5

**Comment by thehannahlerman** [comment]
This should be fixed now when you create a new labor market. Until we reindex, it will still be an issue for the old markets
