### ISSUE TITLE
Update `Review & Score` button on a challenge if not signaled to `Claim to Review`

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#557]
right now I can see the button and click and it fails with 
<img width="401" alt="Screenshot 2023-03-20 at 11 29 45 AM" src="https://user-images.githubusercontent.com/7825326/226388905-2443bbe1-0673-4657-ac5c-c5b635984f86.png">

can we know a user hasn't signaled so we can update the button?

I'd instead show Claim to Review if the user still needs to signal. then once they enter a score on a given submission I'd have copy that says "You scored this a [score]" or something

**Comment by nftchance** [comment]
Following.

**Comment by gnomadic** [comment]
wonder if it's possible to also hide the submit review button once I've already reviewed, because it will fail with an "already reviewed" error
