### ISSUE TITLE
Bug - Various counts are off

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#567]
Submission count: https://beta.metricsdao.xyz/app/market/0xF1B73811AB55F4880B63cBfCF20cB6140E05C066/request/1

Challenges count: https://beta.metricsdao.xyz/app/market/0xF1B73811AB55F4880B63cBfCF20cB6140E05C066

Challenges list missing count label altogether - should have one like Marketplaces does: https://beta.metricsdao.xyz/app/challenges
![Screen Shot 2023-03-20 at 3 39 18 PM](https://user-images.githubusercontent.com/93347510/226448148-8863d7a4-f2c8-4b64-acb2-5bba8c9d9e1f.png)

My Rewards

Incorrectly says I have 3 Rewards when I'm viewing the Addresses tab
![Image](https://user-images.githubusercontent.com/93347510/226453100-60fda31d-b9f2-4e59-bb52-9a1d305bf85c.png)

Then correctly says I have 2 Rewards when I'm viewing the Rewards tab

![Image](https://user-images.githubusercontent.com/93347510/226453113-e6aaf303-aca4-47ae-879d-e2d31fe44a60.png)

Rewards in main nav never shows count, but should show the count of unclaimed rewards, in this case 1
![Image](https://user-images.githubusercontent.com/93347510/226453126-e4bba995-6364-45a0-9eba-666a16399170.png)

**Comment by sebruiz** [comment]
Think I know the issue with the counts being off. When we do `getIndexed` there’s the race condition between the indexer and the web url. This is handling ok on an upsert (deterministic), but breaks down when there’s a side-effect like incrementing `serviceRequestCount`
