### ISSUE TITLE
[public report]: Switch Chain to Polygon

### ISSUE THREAD

**Issue by ltirrell** [MetricsDAO/xyz#572]
### User Impacted

0xb40c994680dd68A63f7ED94608F8B524f6c569de

### Discord ID (including number)

LTirrell#4794

### Workflow Impacted

Analyze

### Feature Impacted

Other

### Issue description

Clicking "Switch Chain" when Metamask is set to Ethereum doesn't give a dialog to switch to Polygon, it just shows user information. I am able to sign the message while on Eth network. Then when i manually switch to Polygon for the first time, I am logged out and have to re-verify the message
![Screenshot from 2023-03-20 12-01-51](https://user-images.githubusercontent.com/5582150/226457360-fcc3bc3e-9e18-4cb3-9408-780cf20d279f.png)

### Blocking

no it is not

**Comment by drakedanner** [comment]
Was going to report this one, but see it's already here!

In the past, the Switch Chain button would also prompt Metamask to open up so the switch could occur.

Should/can we place a "Switch Chain" CTA inside the menu that pulls up Metamask?

![image](https://user-images.githubusercontent.com/11461756/229174923-a86dfb42-1d0f-4f63-b323-bce9127da3fd.png)
