### ISSUE TITLE
[public report]: Able to claim and submit to my own Challenge

### ISSUE THREAD

**Issue by ltirrell** [MetricsDAO/xyz#574]
### User Impacted

0xb40c994680dd68A63f7ED94608F8B524f6c569de

### Discord ID (including number)

LTirrell#4794

### Workflow Impacted

Analyze

### Feature Impacted

Claim to Submit

### Issue description

I can create a challenge in a marketplace I created, then also submit to that challenge.

https://beta.metricsdao.xyz/app/market/0x2b8f7f727ddAE025c94EaEcC63315cb822EB3137/request/1

I am not sure if this is unexpected behavior or not, but I thought challenge creators cannot submit to their own challenge

### Blocking

yes it is

**Comment by gnomadic** [comment]
cc @elisemarika @nftchance 

I believe this is ok behaivor - the challenge creators submission will be still be reviewed independently and they will receive payout dependant on the relative quality of other submissions.

The other challenge - we can't quite stop this, the challenge creator could just create a new wallet and submit

**Comment by nftchance** [comment]
Worth thinking through -- It will still be reviewed independently unless they choose it not to which would basically mean it's a faucet if someone were using a reputational token.

Potentially worth preventing, but does make sense to allow them to be reviewer at minimum.

**Comment by elisemarika** [comment]
I also think this is okay behavior. they cannot review their own submission, so it's up to the other reviewers to form consensus
