### ISSUE TITLE
[public report]: Sorting by submit deadline or review deadline gives an error

### ISSUE THREAD

**Issue by realguy33** [MetricsDAO/xyz#601]
### User Impacted

0x86874Bf84F0D27dcfc6c4c34ab99AAD8Ced8d892

### Discord ID (including number)

yesyes#4764

### Workflow Impacted

Analyze

### Feature Impacted

Other

### Issue description

Trying to sort by 'submit deadline' or 'review deadline' in the challenges tab(https://beta.metricsdao.xyz/app/challenges) gives an application error. 
![mdaoerror](https://user-images.githubusercontent.com/70895323/226757040-40e9240b-4891-41e9-b58d-e4a75e661011.png)

### Blocking

no it is not

### Relevant log output

```shell
Error: Unexpected Server Error
    at handleDataRequestRR (/myapp/build/server.js:38908:35)
    at requestHandler (/myapp/build/server.js:38838:22)
    at /myapp/build/server.js:40008:26
```

**Comment by gnomadic** [comment]
ah!  nice catch!  we can get this one fixed
