### ISSUE TITLE
Potential duplicate count issue

### ISSUE THREAD

**Issue by thekakamora** [MetricsDAO/xyz#602]
### User Impacted

0x20e0F0d4FFfB9A8b4C6d48F68b1058A294503886

### Discord ID (including number)

kakamora#2549

### Workflow Impacted

Analyze

### Feature Impacted

Other

### Issue description

The count of values shown seems to be double 

The page https://beta.metricsdao.xyz/app/market/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F/request/1 shows we have 4 submission, but actual value is 2. 

The page https://beta.metricsdao.xyz/app/market/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F shows we have 2 challenges, but the actual value is 1.

### Blocking

no it is not

**Comment by gnomadic** [comment]
we're on this one!  it's being tracked in issue #567
