### ISSUE TITLE
Protocol layer - maxSubmissions on a Challenge

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#609]
**Job to be Done**
As a Sponsor, when launching a Challenge I want the ability to set a maximum submissions limit, so that I can more flexibly gate how many analysts can claim (signal) on my Challenge, and optimize my budgets and incentives in a way that best suits me

**Requirements**
- Sponsors can optionally set a maximum submissions limit when launching a Challenge. limit = claim limit

**Comment by nftchance** [comment]
Resolved in pending commit -- Will return with documentation and links.
