### ISSUE TITLE
Protocol layer - Binary enforcement criteria (pass/fail scoring)

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#620]

**Comment by nftchance** [comment]
@masonchain Can this be accomplished with a Likert that is already developed?

Functionality needed:

> User has two inputs.
> 
> Input 1 is 0.
> Input 2 is 100.
> 
> Still use existing framework rules for distribution.

The reason of requirement for collective enforcement is that someone erroneously submitting a grade that is not accurate to the binary state of completion would be a critical failure. Therefore, although the input may be pass/fail it would be advised that we maintain the existing backend logic.

Therefore, the primary need here is that of the ability to have a single all-or-nothing grading scheme. @masonchain, can you confirm that this is already supported at the protocol level and merely a matter of implementation at the app layer?

**Comment by masonchain** [comment]
It is supported by the currently deployed version and just needs a configuration that matches that set up. Setting just 2 distribution buckets and having the cutoff for "Pass" be a 50 or 70 is all that is needed.

The current version doesn't currently enforce that an incoming review be strictly 0 or 1, but I've been cooking up on a better way to handle the enforcement configuration that could handle that as well.

**Comment by masonchain** [comment]
https://docs.google.com/spreadsheets/d/1UxsEQ_EuKyUjeAgmG6XLKt9gg9sHkbLmfkCnKQaOT8g/edit#gid=318861580

![Screen Shot 2023-03-24 at 10 19 39 AM](https://user-images.githubusercontent.com/33527785/227567373-eb8b9049-f760-41fb-a316-2bba8954ab18.png)

**Comment by nftchance** [comment]
Okay, so the answer is no. I just realized Likert had hard-coded grade options. Even if it were dynamic, it would not work.

We will have to make an entirely custom module for this, and the app team will have to build a custom process to handle this.

**Comment by nftchance** [comment]
Checking back in here to see if this was ever fully specced?

**Comment by nftchance** [comment]
Resolved in pending commit and will loop back with documentation and links.
