### ISSUE TITLE
UI Improvements: Completed vs active challenges, counters and page scrolling

### ISSUE THREAD

**Issue by thekakamora** [MetricsDAO/xyz#622]
### User Impacted

0x20e0F0d4FFfB9A8b4C6d48F68b1058A294503886

### Discord ID (including number)

kakamora#2549

### Workflow Impacted

Analyze

### Feature Impacted

Create Marketplace

### Issue description

1. Can you please consider distinguishing completed vs active challenges on UI? 
2. Also the count of challenges is still off. We have two challenges but the screeshot shows 3.
3. click on tabs "Challenges", "Prerequisites" and "Rewards" scrolls the page to the top. We are forced to scroll down to view details.

![image](https://user-images.githubusercontent.com/86695148/227436118-7cbf66a0-00d3-4d5a-a2f4-55e3392e1dc7.png)

### Blocking

no it is not

**Comment by gnomadic** [comment]
couple things in here, cc @elisemarika 

#2 is good - that's a known issue!

#1 - @mahgillis and @A4x1 heads up we should take a pass on styling completed vs active challenges differently that's noticeable at a glance - not sure timing on this but we can figure it out

#3 - @termaatFlipside do you think we can stash scroll position and keep it (if possible) when changing tabs?

**Comment by elisemarika** [comment]
moving to In Design so we can at least solve styling on completed vs. active ASAP - I was thinking that yesterday! @mahgillis @A4x1

**Comment by termaatFlipside** [comment]
@gnomadic Yeah can probably do that scrolling bit

**Comment by mahgillis** [comment]
Here's my suggestion to distinguish between active and past challenges:
[https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=6352%3A17489&t=Q5DlD1t96dObA1pf-1](url)

**Comment by elisemarika** [comment]
@termaatFlipside scope for this issue for now

- page scrolling
- styling to differentiate active vs. completed challenges: https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=6357-18317&t=uWisrLq78wXKdE4m-0

**Comment by sebruiz** [comment]
@termaatFlipside Can probably use this attribute for the scrolling:
https://reactrouter.com/en/main/components/link#preventscrollreset

**Comment by elisemarika** [comment]
@termaatFlipside are you still working on greying out the past challenges? note all styling to differentiate active vs. completed challenges: https://www.figma.com/file/66Myyf1MVmY8UKv7BrVUa5/MDAO-App-Designs?node-id=6357-18317&t=uWisrLq78wXKdE4m-0

**Comment by termaatFlipside** [comment]
@elisemarika yeah that's on the todo list
