### ISSUE TITLE
System allows me to review & score without claiming but throws error

### ISSUE THREAD

**Issue by thekakamora** [MetricsDAO/xyz#623]
### User Impacted

0x20e0F0d4FFfB9A8b4C6d48F68b1058A294503886

### Discord ID (including number)

kakamora#2549

### Workflow Impacted

Analyze

### Feature Impacted

Claim to Review

### Issue description

System allows me to review & score before claiming, but when I try to submit the review it throws an error. Can we disable "Review & Score" button for users who did not claim so that they don't end up in this error situation?

![image](https://user-images.githubusercontent.com/86695148/227442387-f6a17878-44e9-4b61-ab94-f6ac3d1d3a7f.png)

### Blocking

No

**Comment by gnomadic** [comment]
this will be fixed with #557 !
