### ISSUE TITLE
Idea - “Redirecting” text

### ISSUE THREAD

**Issue by sebruiz** [MetricsDAO/xyz#630]
We could show text in our transaction modal that says something like "Redirecting..." to make it more obvious to the user what is happening when the transaction succeeds.

**Comment by drakedanner** [comment]
Don't think this is necessary as long as the redirects are quick enough

**Comment by masonchain** [comment]
@drakedanner This would solve the issue of redirecting wait times mentioned in #790.

Currently the transaction is getting confirmed and we set success on the modal but have aftereffects like processing the logs that cause the gap between modal close and the actual redirect.
