### ISSUE TITLE
Protocol layer - pTokens for Reviewers

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#634]
**Job to be Done**
As a Sponsor, when launching a Challenge I want the ability to define a pToken payout amount for reviewers, so that I can flexibly incentivize peer review for my Challenge, and optimize my budgets and incentives in a way that best suits me

Requirements

Sponsors must set a reviewer pToken and amount and fund them when launching a Challenge

**Comment by nftchance** [comment]
Resolved in pending commit -- Will return with documentation and links.
