### ISSUE TITLE
Update XYZ call to actions to direct to Beta App instead of Notion

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#637]
All call to actions on metricsdao.xyz should match those on beta.metricsdao.xyz to Launch App instead of link to Notion for our public/promoted GTM on Wed 4/5

List from past update: https://github.com/MetricsDAO/xyz/issues/458#issuecomment-1450352021

**Comment by drakedanner** [comment]
With the understanding that we're limited to protocol chain payments only this week, do we want to retain a button out to non-protocol chain paid challenges hosted on Notion, or can we share that through social channels for time being?

**Comment by elisemarika** [comment]
@drakedanner we can handle via discord...I'm sure many people also have that bookmarked
