### ISSUE TITLE
Protocol layer - Bounded payout; don't use reward pool

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#661]
The big shift is just being able to draw against a budget instead of deploying the full pool

**Comment by drakedanner** [comment]
Want to clarify that true "Cost Per Action" behavior will occur if all claims are taken. 

This approach includes enabling claim limits and a pass/fail enforcement criteria (flat reward curve).

**Comment by nftchance** [comment]
> This approach includes enabling claim limits and a pass/fail enforcement criteria (flat reward curve).

Pass/fail configuration of Likert module. We will not establish new enforcement modules until the existing ones are fully implemented in the app layer and then understood by users.

**Comment by drakedanner** [comment]
Working on v2 enforcement and payments and have come across the reality that we cannot support unlimited Submissions or unlimited Reviews.

The limit value for both of these will inform the maximum amount of payout possible per action.

This also empowers the operators to have greatest control over budget. 

They can determine how much each Review will be paid, if less than the limit is reached then the remaining funds can be claimed back by the Sponsor.

In the case of Provider payments, each user will have a potential share of the total pool based on the limits. ie: $1000 in a Challenge with a limit of 10 means that each Provider can earn up to $100. If single user submits to the challenge and scores a 7/10 they may earn $70. Again, the remaining $30 + $900 can be reclaimed by the Sponsor. The amount of payment they receive relative to score can be scaled up and down... scalable likert!

In the case of the limit being met (10 users show up), the experience is similar to the Scalable Likert example we've used with the pool.

**Comment by drakedanner** [comment]
I made a tab in this spreadsheet called Localized Scalable Likert that we can play with https://docs.google.com/spreadsheets/d/1UxsEQ_EuKyUjeAgmG6XLKt9gg9sHkbLmfkCnKQaOT8g/edit?usp=sharing

**Comment by drakedanner** [comment]
Of note, there will be meaningful remainders that can be returned to Sponsors 
![image](https://user-images.githubusercontent.com/11461756/236345546-5c46e04b-30a7-47d7-9ee1-327cb718753b.png)

**Comment by nftchance** [comment]
Resolved in pending commit. Will loop back with documentation and links.

**Comment by drakedanner** [comment]
Link to spreadsheet: https://docs.google.com/spreadsheets/d/1lX4LpG3FgRGFcfRo3rwKTabu_Qk6IP9WgZQ0sNGGDcc/edit?usp=sharing
