### ISSUE TITLE
idea- expose endpoints for getting certain postgres data like how many user wallets are connected and how many claims on certain challenges etc.

### ISSUE THREAD

**Issue by thehannahlerman** [MetricsDAO/xyz#664]

**Comment by thehannahlerman** [comment]
@drakedanner what would be the most valuable info to expose without giving too much?

**Comment by drakedanner** [comment]
@thehannahlerman if we wanted to explore this, I would say we can follow the pattern of what is public onchain already.

After discussing this more with the GTM team, it seems that wallet connections is an interesting top of funnel metric but I don't think that we need to spend time exposing that data as long as the development team retains access and shares updates.

Other data incl Claims can be pulled from the chain!

@nftchance any idea you can think to expose more data via API? This feels like we could _maybe_ close for now?

**Comment by nftchance** [comment]
I may need more context here, but on our side, we use asynchronous KPI calculations and avoid storing them in the database. 

Additional KPIs/data doesn't solve a problem for anyone and is not something I imagine is worth spending time on further validated by a MetricsDAO member having already created a dashboard -- All the important stuff is onchain or accessible from IPFS!

**Comment by thehannahlerman** [comment]
Basically I just wasn't sure if connected wallets to the app etc was going to continue to be an important metric. But I agree the dashboard and on chain data are much better. Will close this out in that case
