### ISSUE TITLE
[public report]: 

### ISSUE THREAD

**Issue by cristinatinto** [MetricsDAO/xyz#683]
### User Impacted

0x2a535AF5A82Bc9c6a3369229446D599577E3e478

### Discord ID (including number)

cristinatinto#3946

### Workflow Impacted

Analyze

### Feature Impacted

Enter Submission

### Issue description

I have sent an incorrect link in the Optimism bounty. There is not any button to change it. Could you change it? This is the correct one: 
https://flipsidecrypto.xyz/cristinatinto/exploring-fees-on-optimism-GniSQU

### Blocking

no it is not

**Comment by gnomadic** [comment]
hey everything is on-chain so editing doesn't quite work!  We are investigating letting people update their submissions, but that might open the door to potential abuse so we have to really mindful.

For this specific marketplace and challenge, you can create a new wallet and submit an entirely new submission - if you do receive rewards for your work, you can set your original main wallet as the payout address.
