### ISSUE TITLE
Bug - Submissions with Score 0 Missing UI Element

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#696]
https://www.loom.com/share/7587ac2f778a41b4b541eab724070dc1

On the Submission View, there is a UI element for the score title and score value.

![image](https://user-images.githubusercontent.com/11461756/232502499-ec96cda5-05d7-4d38-b21a-dbdef75408fc.png)

On Submissions with a score of 0, the element is not shown properly.

![image](https://user-images.githubusercontent.com/11461756/232502600-6669c6b3-1dad-4196-9ac1-9075d31acde7.png)

https://metricsdao.xyz/app/market/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F/submission/48?sortBy=blockTimestamp

**Comment by sebruiz** [comment]
Resolved in https://github.com/MetricsDAO/xyz/pull/697
