### ISSUE TITLE
V2 migration - Create submission redirect

### ISSUE THREAD

**Issue by sebruiz** [MetricsDAO/xyz#790]
After a transaction resolves, the app will redirect to the page immediately after the transaction confirms. 

If we don't have this, we risk the user executing a transaction twice because they'll just be sitting in the form page

**Comment by drakedanner** [comment]
Issues related to this in the past:
- User sends tx, page does not redirect, user is at risk of re-submitting 
- Where is the data needed to enable the re-direct?
