### ISSUE TITLE
migrate legacy showcase page into app

### ISSUE THREAD

**Issue by sebruiz** [MetricsDAO/xyz#798]
So that we may deprecate the old infra in Fly

**Comment by drakedanner** [comment]
Related to V1 of the Metrics app.

Also related to https://legacy.metricsdao.xyz/showcase ? 

@thekakamora can you please share how this data is fed into the Legacy showcase page.

@catscatscode keeping you in the loop too.

**Comment by thekakamora** [comment]
@drakedanner the legacy showcase page is powered by https://www.algolia.com/. Meg & GJ owns the account.

**Comment by drakedanner** [comment]
@gnomadic checking with @catscatscode if migration done is adequate
