### ISSUE TITLE
Add Docs to Header & Footer

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/xyz#8]
Add a link to https://docs.metricsdao.xyz/ to the header and footer of the homepage with a relevant icon (book, document).

I am not sure of the icon set. 

It can be placed to the right end in the header: 
![image](https://user-images.githubusercontent.com/11461756/166812165-e46dd9fe-28f8-46d5-bb7e-96763544b172.png)

It can be placed on the bottom of the list in the footer:
![image](https://user-images.githubusercontent.com/11461756/166812410-4d9a3da5-2d64-43b6-a88a-08bcd2fd328c.png)

The words can be "Docs"

**Comment by D0R11** [comment]
Hello, I'll take this issue.

**Comment by D0R11** [comment]
I started a new branch but I can't make a pull request. Can someone give me access? Thanks
