### ISSUE TITLE
Update T&C

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/xyz#806]
https://docs.google.com/document/d/1VwgYiEEztVrON7HTVn33jTr1wIKgr09AEKYO6FaJX70/edit

**Comment by termaatFlipside** [comment]
@gnomadic to clarify does that doc replace this entire page [https://metricsdao.xyz/terms](https://metricsdao.xyz/terms)?

**Comment by gnomadic** [comment]
confirming with legal!
